### ISSUE TITLE
Widget actions do not work 'out of the box' [BUG]

### ISSUE THREAD

**Issue by resiehnnes** [luisbocanegra/plasma-panel-spacer-extended#34]
Widget defaults to 'qdbus6' as 'qdbus executable' in 'behavior' settings on my system thus not allowing me to use any default actions. When hovering on widget the tooltip shows default actions, but going to widget settings everything is disabled. Setting  'qdbus executable' to 'qdbus' allows me to select and set actions, but if I want to have predefined actions I have to set it up manually.

Fedora Linux 40 (KDE Plasma 6.0.4), Wayland

**Comment by luisbocanegra** [comment]
Huh? That's really bad. The reason this happens is because I get all the shortcuts in the system using qdbus, then look for the previously selected action. Since it couldn't find the action (because the shortcuts couldn't be loaded) it defaults to Disabled.

I think a way to solve this could be by loading the Actions until the correct qdbus is set. Maybe I can try to find the correct qdbus by looping through the usual names and warn in case it needs to be setup manually.

**Comment by luisbocanegra** [comment]
Commit https://github.com/luisbocanegra/plasma-panel-spacer-extended/commit/4305e749cf407942cba3d8fc21d6fc5d87f74b67 should fix this.

Actions are now changed by clicking on the selected action so it doesn't matter if qdbus is not found.

**Comment by resiehnnes** [comment]
@luisbocanegra  Build 1.7.1 works as you described :+1: Guess I can close this one now.
